USE ROLE      VERTIV_PLATFORM_ADMIN;
USE WAREHOUSE INGEST_WH;
USE DATABASE  VERTIV_CONFIG;

CREATE SCHEMA IF NOT EXISTS METADATA;
CREATE SCHEMA IF NOT EXISTS LINEAGE;
CREATE SCHEMA IF NOT EXISTS REFERENCE;

CREATE OR REPLACE TABLE VERTIV_CONFIG.METADATA.SOURCE_TO_TARGET_MAP (
  STT_ID            NUMBER        AUTOINCREMENT PRIMARY KEY,
  SOURCE_SYSTEM     VARCHAR(50)   NOT NULL,
  SOURCE_REGION     VARCHAR(30)   NOT NULL,
  SOURCE_SCHEMA     VARCHAR(100)  NOT NULL,
  SOURCE_TABLE      VARCHAR(100)  NOT NULL,
  SOURCE_COLUMN     VARCHAR(100)  NOT NULL,
  TARGET_LAYER      VARCHAR(20)   NOT NULL,
  TARGET_DATABASE   VARCHAR(100)  NOT NULL,
  TARGET_SCHEMA     VARCHAR(100)  NOT NULL,
  TARGET_TABLE      VARCHAR(100)  NOT NULL,
  TARGET_COLUMN     VARCHAR(100)  NOT NULL,
  TRANSFORMATION    VARCHAR(2000),
  DATA_TYPE         VARCHAR(50),
  IS_PK_COLUMN      BOOLEAN       DEFAULT FALSE,
  IS_HASH_KEY_PART  BOOLEAN       DEFAULT FALSE,
  IS_NULLABLE       BOOLEAN       DEFAULT TRUE,
  IS_PII            BOOLEAN       DEFAULT FALSE,
  DQ_RULE_IDS       VARCHAR(500),
  IS_ACTIVE         BOOLEAN       DEFAULT TRUE,
  EFFECTIVE_DATE    DATE          DEFAULT CURRENT_DATE(),
  CREATED_BY        VARCHAR(100)  DEFAULT CURRENT_USER(),
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE VERTIV_CONFIG.METADATA.DQ_RULES (
  RULE_ID           NUMBER        AUTOINCREMENT PRIMARY KEY,
  RULE_NAME         VARCHAR(200)  NOT NULL,
  DAMA_DIMENSION    VARCHAR(50)   NOT NULL,
  SOURCE_SYSTEM     VARCHAR(50),
  TARGET_TABLE      VARCHAR(200),
  TARGET_COLUMN     VARCHAR(100),
  RULE_EXPRESSION   VARCHAR(4000) NOT NULL,
  SEVERITY          VARCHAR(20)   DEFAULT 'ERROR',
  ACTION_ON_FAIL    VARCHAR(50)   DEFAULT 'REJECT',
  ERROR_MESSAGE     VARCHAR(500),
  IS_ACTIVE         BOOLEAN       DEFAULT TRUE,
  CREATED_BY        VARCHAR(100)  DEFAULT CURRENT_USER(),
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE VERTIV_CONFIG.METADATA.BATCH_RUN_LOG (
  RUN_ID            NUMBER        AUTOINCREMENT PRIMARY KEY,
  BATCH_ID          VARCHAR(36)   NOT NULL,
  PIPELINE_NAME     VARCHAR(200)  NOT NULL,
  SOURCE_SYSTEM     VARCHAR(50),
  TARGET_LAYER      VARCHAR(20),
  TARGET_TABLE      VARCHAR(200),
  STATUS            VARCHAR(20)   DEFAULT 'RUNNING',
  RECORDS_READ      NUMBER        DEFAULT 0,
  RECORDS_LOADED    NUMBER        DEFAULT 0,
  RECORDS_REJECTED  NUMBER        DEFAULT 0,
  START_TIME        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  END_TIME          TIMESTAMP_NTZ,
  DURATION_SECONDS  NUMBER,
  ERROR_MESSAGE     VARCHAR(4000),
  WAREHOUSE_USED    VARCHAR(100)  DEFAULT CURRENT_WAREHOUSE(),
  RUN_BY            VARCHAR(100)  DEFAULT CURRENT_USER()
);

CREATE OR REPLACE TABLE VERTIV_CONFIG.REFERENCE.CURRENCY (
  CURRENCY_CODE  VARCHAR(3)   PRIMARY KEY,
  CURRENCY_NAME  VARCHAR(100),
  FX_TO_USD      NUMBER(10,6) DEFAULT 1.0,
  IS_ACTIVE      BOOLEAN DEFAULT TRUE
);

INSERT INTO VERTIV_CONFIG.REFERENCE.CURRENCY VALUES
  ('USD','US Dollar',1.000000,TRUE),('EUR','Euro',1.080000,TRUE),
  ('GBP','British Pound',1.270000,TRUE),('CHF','Swiss Franc',1.100000,TRUE),
  ('CAD','Canadian Dollar',0.740000,TRUE),('AUD','Australian Dollar',0.650000,TRUE),
  ('JPY','Japanese Yen',0.006700,TRUE),('CNY','Chinese Yuan',0.140000,TRUE),
  ('INR','Indian Rupee',0.012000,TRUE),('SGD','Singapore Dollar',0.740000,TRUE),
  ('BRL','Brazilian Real',0.200000,TRUE),('MXN','Mexican Peso',0.059000,TRUE),
  ('AED','UAE Dirham',0.272000,TRUE),('SAR','Saudi Riyal',0.267000,TRUE),
  ('ZAR','South African Rand',0.054000,TRUE);

CREATE OR REPLACE TABLE VERTIV_CONFIG.REFERENCE.COUNTRY (
  COUNTRY_CODE  VARCHAR(3)   PRIMARY KEY,
  COUNTRY_NAME  VARCHAR(100),
  REGION        VARCHAR(30),
  SUB_REGION    VARCHAR(50),
  IS_EU_GDPR    BOOLEAN DEFAULT FALSE,
  ERP_SYSTEM    VARCHAR(20)
);

INSERT INTO VERTIV_CONFIG.REFERENCE.COUNTRY VALUES
  ('DEU','Germany','EUROPE','DACH',TRUE,'SAP'),
  ('GBR','United Kingdom','EUROPE','UK and Ireland',TRUE,'SAP'),
  ('FRA','France','EUROPE','Western Europe',TRUE,'SAP'),
  ('NLD','Netherlands','EUROPE','Benelux',TRUE,'SAP'),
  ('SWE','Sweden','EUROPE','Nordics',TRUE,'SAP'),
  ('ITA','Italy','EUROPE','Southern Europe',TRUE,'SAP'),
  ('ESP','Spain','EUROPE','Southern Europe',TRUE,'SAP'),
  ('CHE','Switzerland','EUROPE','DACH',FALSE,'SAP'),
  ('USA','United States','AMERICAS','North America',FALSE,'JDE'),
  ('CAN','Canada','AMERICAS','North America',FALSE,'JDE'),
  ('BRA','Brazil','AMERICAS','Latin America',FALSE,'JDE'),
  ('MEX','Mexico','AMERICAS','Latin America',FALSE,'JDE'),
  ('ARE','UAE','EMEA','Gulf',FALSE,'QAD'),
  ('SAU','Saudi Arabia','EMEA','Gulf',FALSE,'QAD'),
  ('ZAF','South Africa','EMEA','Africa',FALSE,'QAD'),
  ('IND','India','APAC','South Asia',FALSE,'QAD'),
  ('SGP','Singapore','APAC','Southeast Asia',FALSE,'QAD');

CREATE OR REPLACE TABLE VERTIV_CONFIG.LINEAGE.DATA_LINEAGE (
  LINEAGE_ID      NUMBER        AUTOINCREMENT PRIMARY KEY,
  BATCH_ID        VARCHAR(36),
  SOURCE_LAYER    VARCHAR(20),
  SOURCE_TABLE    VARCHAR(300),
  TARGET_LAYER    VARCHAR(20),
  TARGET_TABLE    VARCHAR(300),
  TRANSFORMATION  VARCHAR(1000),
  RECORD_COUNT    NUMBER,
  RUN_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT SELECT ON ALL TABLES IN SCHEMA VERTIV_CONFIG.METADATA  TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA VERTIV_CONFIG.REFERENCE TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA VERTIV_CONFIG.LINEAGE   TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE  ON SCHEMA VERTIV_CONFIG.REFERENCE               TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA VERTIV_CONFIG.REFERENCE TO ROLE VERTIV_GLOBAL_ANALYST;

SELECT 'Done' AS STATUS;
