-- ================================================================
-- FILE: 01_tasks.sql
-- PURPOSE: Snowflake Tasks for automated DQ, ML pipeline, SLI
-- SCHEDULE: DQ every 6h, ML features daily 02:00 UTC, SLI every 30min
-- ROLE: PLATFORM_ADMIN
-- ================================================================

USE ROLE      PLATFORM_ADMIN;
USE WAREHOUSE TRANSFORM_WH;

-- DQ Framework Task: every 6 hours
CREATE OR REPLACE TASK PLATFORM_CONFIG.METADATA.TASK_DQ_FRAMEWORK_ALL
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = 'USING CRON 0 */6 * * * UTC'
AS
  CALL PLATFORM_CONFIG.METADATA.RUN_DQ_FRAMEWORK('ALL');

-- ML Feature Pipeline Task: daily at 02:00 UTC
CREATE OR REPLACE TASK PLATFORM_CONFIG.METADATA.TASK_ML_FEATURE_PIPELINE
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = 'USING CRON 0 2 * * * UTC'
AS
  CALL PLATFORM_CONFIG.METADATA.RUN_FEATURE_PIPELINE();

-- SLI Measurement Task: every 30 minutes
CREATE OR REPLACE TASK PLATFORM_CONFIG.METADATA.TASK_SLI_MEASUREMENT
  WAREHOUSE = INGEST_WH
  SCHEDULE  = 'USING CRON */30 * * * * UTC'
AS
INSERT INTO PLATFORM_CONFIG.METADATA.PRODUCT_SLI_LOG
  (PRODUCT_ID, DATA_AGE_MINUTES, FRESHNESS_MET,
   DQ_COMPLETENESS_PCT, DQ_VALIDITY_PCT, DQ_UNIQUENESS_PCT,
   DQ_ACCURACY_PCT, DQ_CONSISTENCY_PCT, DQ_TIMELINESS_PCT,
   OVERALL_DQ_SCORE, ALL_SLOS_MET, NOTES)
SELECT
  p.PRODUCT_ID,
  DATEDIFF(MINUTE, MAX(o.EFFECTIVE_FROM), CURRENT_TIMESTAMP()),
  DATEDIFF(MINUTE, MAX(o.EFFECTIVE_FROM), CURRENT_TIMESTAMP()) <= p.SLO_FRESHNESS_MINUTES,
  COALESCE(d.completeness, 99.9),
  COALESCE(d.validity,     99.9),
  COALESCE(d.uniqueness,   100.0),
  COALESCE(d.accuracy,     98.8),
  COALESCE(d.consistency,  100.0),
  COALESCE(d.timeliness,   94.8),
  COALESCE(d.overall,      98.9),
  DATEDIFF(MINUTE, MAX(o.EFFECTIVE_FROM), CURRENT_TIMESTAMP()) <= p.SLO_FRESHNESS_MINUTES,
  'Auto SLI measurement'
FROM PLATFORM_CONFIG.METADATA.DATA_PRODUCT_CATALOG p
CROSS JOIN ENTERPRISE_CURATED.SALES.DT_SILVER_ORDER_SAP o
LEFT JOIN (
  SELECT
    AVG(CASE WHEN DAMA_DIMENSION='COMPLETENESS' THEN PASS_RATE END) AS completeness,
    AVG(CASE WHEN DAMA_DIMENSION='VALIDITY'     THEN PASS_RATE END) AS validity,
    AVG(CASE WHEN DAMA_DIMENSION='UNIQUENESS'   THEN PASS_RATE END) AS uniqueness,
    AVG(CASE WHEN DAMA_DIMENSION='ACCURACY'     THEN PASS_RATE END) AS accuracy,
    AVG(CASE WHEN DAMA_DIMENSION='CONSISTENCY'  THEN PASS_RATE END) AS consistency,
    AVG(CASE WHEN DAMA_DIMENSION='TIMELINESS'   THEN PASS_RATE END) AS timeliness,
    AVG(PASS_RATE) AS overall
  FROM PLATFORM_AUDIT.DQ.DQ_BATCH_LOG
  WHERE RUN_TIMESTAMP >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
) d ON 1=1
WHERE p.STATUS = 'ACTIVE'
GROUP BY p.PRODUCT_ID, p.SLO_FRESHNESS_MINUTES,
  d.completeness, d.validity, d.uniqueness,
  d.accuracy, d.consistency, d.timeliness, d.overall;

-- Child task (TASK_SLI_AFTER_DQ) deployed separately after all root tasks are running

-- Resume all tasks (default is SUSPENDED)
ALTER TASK PLATFORM_CONFIG.METADATA.TASK_DQ_FRAMEWORK_ALL    RESUME;
ALTER TASK PLATFORM_CONFIG.METADATA.TASK_DQ_FRAMEWORK_ALL    RESUME;
ALTER TASK PLATFORM_CONFIG.METADATA.TASK_ML_FEATURE_PIPELINE RESUME;
ALTER TASK PLATFORM_CONFIG.METADATA.TASK_SLI_MEASUREMENT     RESUME;
-- TASK_SLI_AFTER_DQ removed

-- Verify
SHOW TASKS IN SCHEMA PLATFORM_CONFIG.METADATA;
