-- Run as VERTIV_PLATFORM_ADMIN
-- Adds ACCESS_REQUESTS table to VERTIV_AUDIT for marketplace access logging

USE DATABASE VERTIV_AUDIT;
USE SCHEMA PUBLIC;
USE WAREHOUSE TRANSFORM_WH;

CREATE TABLE IF NOT EXISTS ACCESS_REQUESTS (
    TICKET_ID       VARCHAR(50)     NOT NULL PRIMARY KEY,
    PRODUCT_ID      VARCHAR(20)     NOT NULL,
    REQUESTER_NAME  VARCHAR(200)    NOT NULL,
    REQUESTER_EMAIL VARCHAR(320)    NOT NULL,
    JUSTIFICATION   VARCHAR(2000),
    STATUS          VARCHAR(20)     DEFAULT 'PENDING',
    REQUESTED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT     TIMESTAMP_NTZ,
    RESOLVED_BY     VARCHAR(200),
    NOTES           VARCHAR(2000),

    CONSTRAINT chk_status CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'REVOKED'))
);

-- Grant INSERT to the role used by Lambda
GRANT INSERT, SELECT ON TABLE ACCESS_REQUESTS TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT INSERT ON TABLE ACCESS_REQUESTS TO ROLE VERTIV_GLOBAL_ANALYST;

-- View for reporting
CREATE OR REPLACE VIEW V_ACCESS_REQUESTS_SUMMARY AS
SELECT
    PRODUCT_ID,
    COUNT(*) AS TOTAL_REQUESTS,
    COUNT_IF(STATUS = 'APPROVED') AS APPROVED,
    COUNT_IF(STATUS = 'PENDING') AS PENDING,
    COUNT_IF(STATUS = 'REJECTED') AS REJECTED,
    MAX(REQUESTED_AT) AS LAST_REQUEST
FROM ACCESS_REQUESTS
GROUP BY PRODUCT_ID;
