-- ================================================================
-- FILE: 02_roles_rbac.sql
-- PURPOSE: Create all roles, hierarchy, and warehouse/database grants
-- ROLE: SECURITYADMIN
-- RUN ORDER: 2nd
-- ESTIMATED TIME: ~1 minute
-- ================================================================

USE ROLE SECURITYADMIN;

-- ── 1. CREATE ROLES ───────────────────────────────────────────
-- Named after function, not person. Principle of least privilege.

-- Top-level platform role
CREATE ROLE IF NOT EXISTS VERTIV_PLATFORM_ADMIN
  COMMENT = 'Full platform: config, audit, all layers, all sources. Assigned to data engineers.';

-- Cross-region BI analyst (Gold layer, all regions, PII masked)
CREATE ROLE IF NOT EXISTS VERTIV_GLOBAL_ANALYST
  COMMENT = 'Gold layer read, all regions, PII masked via Dynamic Data Masking policies.';

-- Region-specific readers (Silver layer row-access-policy filtered)
CREATE ROLE IF NOT EXISTS VERTIV_SAP_EUROPE_READER
  COMMENT = 'Silver/Gold read - EUROPE region only. Maps to SAP S/4HANA data.';

CREATE ROLE IF NOT EXISTS VERTIV_JDE_AMERICAS_READER
  COMMENT = 'Silver/Gold read - AMERICAS region only. Maps to JDE ERP data.';

CREATE ROLE IF NOT EXISTS VERTIV_QAD_EMEA_READER
  COMMENT = 'Silver/Gold read - EMEA region only. Maps to QAD ERP data.';

-- Functional roles
CREATE ROLE IF NOT EXISTS VERTIV_ML_ENGINEER
  COMMENT = 'ML Feature Store, Snowpark Python, Model Registry. No raw Bronze access.';

CREATE ROLE IF NOT EXISTS VERTIV_DATA_PRODUCT_OWNER
  COMMENT = 'Publish and manage Data Products in Snowflake Marketplace. Read audit DB.';

CREATE ROLE IF NOT EXISTS VERTIV_FINANCE_ANALYST
  COMMENT = 'Revenue analytics Gold views. Sensitive margin columns masked below VP level.';

CREATE ROLE IF NOT EXISTS VERTIV_EXEC_VP
  COMMENT = 'Full Gold analytics, unmasked revenue and margin. Executive view.';

-- ── 2. ROLE HIERARCHY ─────────────────────────────────────────
-- SYSADMIN > PLATFORM_ADMIN > GLOBAL_ANALYST > regional readers

GRANT ROLE VERTIV_PLATFORM_ADMIN      TO ROLE SYSADMIN;
GRANT ROLE VERTIV_GLOBAL_ANALYST      TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT ROLE VERTIV_ML_ENGINEER         TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT ROLE VERTIV_DATA_PRODUCT_OWNER  TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT ROLE VERTIV_FINANCE_ANALYST     TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT ROLE VERTIV_EXEC_VP             TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT ROLE VERTIV_SAP_EUROPE_READER   TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT ROLE VERTIV_JDE_AMERICAS_READER TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT ROLE VERTIV_QAD_EMEA_READER     TO ROLE VERTIV_GLOBAL_ANALYST;

-- ── 3. WAREHOUSE GRANTS ───────────────────────────────────────
GRANT USAGE ON WAREHOUSE INGEST_WH    TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE VERTIV_FINANCE_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE VERTIV_EXEC_VP;
GRANT USAGE ON WAREHOUSE ML_WH        TO ROLE VERTIV_ML_ENGINEER;

-- ── 4. DATABASE-LEVEL GRANTS ──────────────────────────────────

-- BRONZE (RAW): platform admin only - no analysts touch raw
GRANT USAGE ON DATABASE VERTIV_RAW TO ROLE VERTIV_PLATFORM_ADMIN;

-- SILVER (CURATED): admin + regional readers (row policy filters data)
GRANT USAGE ON DATABASE VERTIV_CURATED TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE ON DATABASE VERTIV_CURATED TO ROLE VERTIV_SAP_EUROPE_READER;
GRANT USAGE ON DATABASE VERTIV_CURATED TO ROLE VERTIV_JDE_AMERICAS_READER;
GRANT USAGE ON DATABASE VERTIV_CURATED TO ROLE VERTIV_QAD_EMEA_READER;

-- GOLD (ANALYTICS): all analyst roles
GRANT USAGE ON DATABASE VERTIV_ANALYTICS TO ROLE VERTIV_GLOBAL_ANALYST;
GRANT USAGE ON DATABASE VERTIV_ANALYTICS TO ROLE VERTIV_ML_ENGINEER;
GRANT USAGE ON DATABASE VERTIV_ANALYTICS TO ROLE VERTIV_FINANCE_ANALYST;
GRANT USAGE ON DATABASE VERTIV_ANALYTICS TO ROLE VERTIV_EXEC_VP;

-- DATA PRODUCTS: product owners publish, analysts consume
GRANT USAGE ON DATABASE VERTIV_PRODUCTS TO ROLE VERTIV_DATA_PRODUCT_OWNER;
GRANT USAGE ON DATABASE VERTIV_PRODUCTS TO ROLE VERTIV_GLOBAL_ANALYST;

-- CONFIG + AUDIT: admin + product owners (to view DQ metrics)
GRANT USAGE ON DATABASE VERTIV_CONFIG TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE ON DATABASE VERTIV_AUDIT  TO ROLE VERTIV_PLATFORM_ADMIN;
GRANT USAGE ON DATABASE VERTIV_AUDIT  TO ROLE VERTIV_DATA_PRODUCT_OWNER;

-- ── 5. ASSIGN YOUR USER ───────────────────────────────────────
-- !! IMPORTANT: Replace YOUR_SNOWFLAKE_USERNAME before running !!
-- GRANT ROLE VERTIV_PLATFORM_ADMIN TO USER YOUR_SNOWFLAKE_USERNAME;

-- ── 6. VERIFY ─────────────────────────────────────────────────
SHOW ROLES LIKE 'VERTIV%';
