-- ================================================================
-- FILE: 02_roles_rbac.sql
-- PURPOSE: Create all roles, hierarchy, and warehouse/database grants
-- ROLE: SECURITYADMIN
-- RUN ORDER: 2nd
-- ESTIMATED TIME: ~1 minute
-- ================================================================

USE ROLE SECURITYADMIN;

-- ── 1. CREATE ROLES ───────────────────────────────────────────
-- Named after function, not person. Principle of least privilege.

-- Top-level platform role
CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN
  COMMENT = 'Full platform: config, audit, all layers, all sources. Assigned to data engineers.';

-- Cross-region BI analyst (Gold layer, all regions, PII masked)
CREATE ROLE IF NOT EXISTS GLOBAL_ANALYST
  COMMENT = 'Gold layer read, all regions, PII masked via Dynamic Data Masking policies.';

-- Region-specific readers (Silver layer row-access-policy filtered)
CREATE ROLE IF NOT EXISTS SAP_EUROPE_READER
  COMMENT = 'Silver/Gold read - EUROPE region only. Maps to SAP S/4HANA data.';

CREATE ROLE IF NOT EXISTS JDE_AMERICAS_READER
  COMMENT = 'Silver/Gold read - AMERICAS region only. Maps to JDE ERP data.';

CREATE ROLE IF NOT EXISTS QAD_EMEA_READER
  COMMENT = 'Silver/Gold read - EMEA region only. Maps to QAD ERP data.';

-- Functional roles
CREATE ROLE IF NOT EXISTS ML_ENGINEER
  COMMENT = 'ML Feature Store, Snowpark Python, Model Registry. No raw Bronze access.';

CREATE ROLE IF NOT EXISTS ENTERPRISE_DATA_PRODUCT_OWNER
  COMMENT = 'Publish and manage Data Products in Snowflake Marketplace. Read audit DB.';

CREATE ROLE IF NOT EXISTS FINANCE_ANALYST
  COMMENT = 'Revenue analytics Gold views. Sensitive margin columns masked below VP level.';

CREATE ROLE IF NOT EXISTS EXEC_VP
  COMMENT = 'Full Gold analytics, unmasked revenue and margin. Executive view.';

-- ── 2. ROLE HIERARCHY ─────────────────────────────────────────
-- SYSADMIN > PLATFORM_ADMIN > GLOBAL_ANALYST > regional readers

GRANT ROLE PLATFORM_ADMIN      TO ROLE SYSADMIN;
GRANT ROLE GLOBAL_ANALYST      TO ROLE PLATFORM_ADMIN;
GRANT ROLE ML_ENGINEER         TO ROLE PLATFORM_ADMIN;
GRANT ROLE ENTERPRISE_DATA_PRODUCT_OWNER  TO ROLE PLATFORM_ADMIN;
GRANT ROLE FINANCE_ANALYST     TO ROLE GLOBAL_ANALYST;
GRANT ROLE EXEC_VP             TO ROLE GLOBAL_ANALYST;
GRANT ROLE SAP_EUROPE_READER   TO ROLE GLOBAL_ANALYST;
GRANT ROLE JDE_AMERICAS_READER TO ROLE GLOBAL_ANALYST;
GRANT ROLE QAD_EMEA_READER     TO ROLE GLOBAL_ANALYST;

-- ── 3. WAREHOUSE GRANTS ───────────────────────────────────────
GRANT USAGE ON WAREHOUSE INGEST_WH    TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE GLOBAL_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE FINANCE_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE EXEC_VP;
GRANT USAGE ON WAREHOUSE ML_WH        TO ROLE ML_ENGINEER;

-- ── 4. DATABASE-LEVEL GRANTS ──────────────────────────────────

-- BRONZE (RAW): platform admin only - no analysts touch raw
GRANT USAGE ON DATABASE ENTERPRISE_RAW TO ROLE PLATFORM_ADMIN;

-- SILVER (CURATED): admin + regional readers (row policy filters data)
GRANT USAGE ON DATABASE ENTERPRISE_CURATED TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON DATABASE ENTERPRISE_CURATED TO ROLE SAP_EUROPE_READER;
GRANT USAGE ON DATABASE ENTERPRISE_CURATED TO ROLE JDE_AMERICAS_READER;
GRANT USAGE ON DATABASE ENTERPRISE_CURATED TO ROLE QAD_EMEA_READER;

-- GOLD (ANALYTICS): all analyst roles
GRANT USAGE ON DATABASE ENTERPRISE_ANALYTICS TO ROLE GLOBAL_ANALYST;
GRANT USAGE ON DATABASE ENTERPRISE_ANALYTICS TO ROLE ML_ENGINEER;
GRANT USAGE ON DATABASE ENTERPRISE_ANALYTICS TO ROLE FINANCE_ANALYST;
GRANT USAGE ON DATABASE ENTERPRISE_ANALYTICS TO ROLE EXEC_VP;

-- DATA PRODUCTS: product owners publish, analysts consume
GRANT USAGE ON DATABASE DATA_PRODUCTS TO ROLE ENTERPRISE_DATA_PRODUCT_OWNER;
GRANT USAGE ON DATABASE DATA_PRODUCTS TO ROLE GLOBAL_ANALYST;

-- CONFIG + AUDIT: admin + product owners (to view DQ metrics)
GRANT USAGE ON DATABASE PLATFORM_CONFIG TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON DATABASE PLATFORM_AUDIT  TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON DATABASE PLATFORM_AUDIT  TO ROLE ENTERPRISE_DATA_PRODUCT_OWNER;

-- ── 5. ASSIGN YOUR USER ───────────────────────────────────────
-- !! IMPORTANT: Replace YOUR_SNOWFLAKE_USERNAME before running !!
-- GRANT ROLE PLATFORM_ADMIN TO USER YOUR_SNOWFLAKE_USERNAME;

-- ── 6. VERIFY ─────────────────────────────────────────────────
SHOW ROLES LIKE 'ENTERPRISE%';
