-- ================================================================
-- FILE: 07_security_data_products.sql
-- PURPOSE: Dynamic Data Masking, Row Access Policies, Secure Views,
--          Snowflake Shares for Marketplace publishing
-- ROLE: ACCOUNTADMIN (for policies) then VERTIV_PLATFORM_ADMIN
-- RUN ORDER: 7th (last SQL file)
-- ================================================================

-- ════════════════════════════════════════════════════════════════
-- PART 1: DYNAMIC DATA MASKING POLICIES
-- ════════════════════════════════════════════════════════════════

USE ROLE ACCOUNTADMIN;

-- PII string masking (names, phones, addresses)
CREATE OR REPLACE MASKING POLICY VERTIV_CONFIG.METADATA.MASK_PII_STRING
AS (VAL VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('VERTIV_EXEC_VP')          THEN VAL
    WHEN IS_ROLE_IN_SESSION('VERTIV_PLATFORM_ADMIN')   THEN VAL
    WHEN IS_ROLE_IN_SESSION('VERTIV_ML_ENGINEER')
         THEN SHA2(VAL)            -- Tokenize for ML: consistent token, no PII
    ELSE '***-MASKED-***'
  END;

-- Email: partial reveal (show domain only to analysts)
CREATE OR REPLACE MASKING POLICY VERTIV_CONFIG.METADATA.MASK_EMAIL
AS (VAL VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('VERTIV_EXEC_VP')        THEN VAL
    WHEN IS_ROLE_IN_SESSION('VERTIV_PLATFORM_ADMIN') THEN VAL
    ELSE '****@' || SPLIT_PART(COALESCE(VAL,'@unknown'), '@', 2)
  END;

-- Financial: mask margins below VP level
CREATE OR REPLACE MASKING POLICY VERTIV_CONFIG.METADATA.MASK_FINANCIAL_NUMBER
AS (VAL NUMBER) RETURNS NUMBER ->
  CASE
    WHEN IS_ROLE_IN_SESSION('VERTIV_EXEC_VP')         THEN VAL
    WHEN IS_ROLE_IN_SESSION('VERTIV_FINANCE_ANALYST')  THEN VAL
    WHEN IS_ROLE_IN_SESSION('VERTIV_PLATFORM_ADMIN')   THEN VAL
    ELSE -1  -- Sentinel: query returns -1 for masked users
  END;

-- Apply masking to Bronze PII columns
ALTER TABLE VERTIV_RAW.SAP_EUROPE.CUSTOMERS
  MODIFY COLUMN PHONE        SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_PII_STRING;
ALTER TABLE VERTIV_RAW.SAP_EUROPE.CUSTOMERS
  MODIFY COLUMN EMAIL        SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_EMAIL;
ALTER TABLE VERTIV_RAW.SAP_EUROPE.CUSTOMERS
  MODIFY COLUMN CREDIT_LIMIT SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_FINANCIAL_NUMBER;

ALTER TABLE VERTIV_RAW.JDE_AMERICAS.CUSTOMERS
  MODIFY COLUMN PHONE        SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_PII_STRING;
ALTER TABLE VERTIV_RAW.JDE_AMERICAS.CUSTOMERS
  MODIFY COLUMN CREDIT_LIMIT SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_FINANCIAL_NUMBER;

ALTER TABLE VERTIV_RAW.QAD_EMEA.CUSTOMERS
  MODIFY COLUMN PHONE        SET MASKING POLICY VERTIV_CONFIG.METADATA.MASK_PII_STRING;

-- ════════════════════════════════════════════════════════════════
-- PART 2: ROW ACCESS POLICIES (regional data isolation)
-- SAP=Europe, JDE=Americas, QAD=EMEA
-- ════════════════════════════════════════════════════════════════

CREATE OR REPLACE ROW ACCESS POLICY VERTIV_CONFIG.METADATA.REGIONAL_DATA_POLICY
AS (SOURCE_REGION VARCHAR) RETURNS BOOLEAN ->
  CASE
    -- Full access: platform admin, global analyst, exec
    WHEN IS_ROLE_IN_SESSION('VERTIV_PLATFORM_ADMIN')     THEN TRUE
    WHEN IS_ROLE_IN_SESSION('VERTIV_GLOBAL_ANALYST')     THEN TRUE
    WHEN IS_ROLE_IN_SESSION('VERTIV_EXEC_VP')            THEN TRUE
    -- Regional readers: only their region
    WHEN IS_ROLE_IN_SESSION('VERTIV_SAP_EUROPE_READER')
         AND SOURCE_REGION = 'EUROPE'                    THEN TRUE
    WHEN IS_ROLE_IN_SESSION('VERTIV_JDE_AMERICAS_READER')
         AND SOURCE_REGION = 'AMERICAS'                  THEN TRUE
    WHEN IS_ROLE_IN_SESSION('VERTIV_QAD_EMEA_READER')
         AND SOURCE_REGION = 'EMEA'                      THEN TRUE
    ELSE FALSE
  END;

-- Apply to Silver layer (filters at the conformed layer)
ALTER TABLE VERTIV_CURATED.SALES.SALES_ORDER
  ADD ROW ACCESS POLICY VERTIV_CONFIG.METADATA.REGIONAL_DATA_POLICY ON (SOURCE_REGION);

ALTER TABLE VERTIV_CURATED.SALES.CUSTOMER
  ADD ROW ACCESS POLICY VERTIV_CONFIG.METADATA.REGIONAL_DATA_POLICY ON (SOURCE_REGION);

-- ════════════════════════════════════════════════════════════════
-- PART 3: DATA PRODUCTS — Secure Views + Snowflake Shares
-- ════════════════════════════════════════════════════════════════

USE ROLE VERTIV_PLATFORM_ADMIN;
USE DATABASE VERTIV_PRODUCTS;

CREATE SCHEMA IF NOT EXISTS SALES_PERFORMANCE;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_360;
CREATE SCHEMA IF NOT EXISTS REVENUE_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS OPPORTUNITY_SIGNALS;

-- ── PRODUCT 1: Sales Performance ─────────────────────────────
-- Stable output contract: v1. Breaking changes require v2 (new view).
CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.SALES_PERFORMANCE.SALES_ORDERS_V1 AS
SELECT
  f.ORDER_HK,
  f.CUSTOMER_HK,
  f.ORDER_DATE,
  f.ORDER_TYPE,
  f.ORDER_STATUS,
  f.CURRENCY_CODE,
  f.NET_AMOUNT_USD,
  f.TOTAL_AMOUNT_USD,
  f.DISCOUNT_PCT,
  f.SOURCE_SYSTEM,
  f.SOURCE_REGION,
  d.YEAR_NUMBER,
  d.QUARTER_NUMBER,
  d.QUARTER_NAME,
  d.MONTH_NUMBER,
  d.MONTH_NAME,
  r.REGION_NAME,
  r.SUB_REGION,
  r.COUNTRY_CODE,
  r.ERP_SYSTEM
FROM VERTIV_ANALYTICS.BI.FACT_SALES_ORDERS f
  LEFT JOIN VERTIV_ANALYTICS.BI.DIM_DATE   d ON f.DATE_KEY  = d.DATE_KEY
  LEFT JOIN VERTIV_ANALYTICS.BI.DIM_REGION r ON f.REGION_SK = r.REGION_SK
;

CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.SALES_PERFORMANCE.REGIONAL_SUMMARY_V1 AS
SELECT * FROM VERTIV_ANALYTICS.BI.MV_REGIONAL_SALES_DAILY
;

CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.SALES_PERFORMANCE.PRODUCT_REVENUE_V1 AS
SELECT * FROM VERTIV_ANALYTICS.BI.MV_PRODUCT_REVENUE_MONTHLY
;

-- ── PRODUCT 2: Customer 360 ───────────────────────────────────
CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.CUSTOMER_360.CUSTOMERS_V1 AS
SELECT
  CUSTOMER_SK,
  MASTER_CUSTOMER_HK,
  CUSTOMER_NAME,
  CUSTOMER_TYPE,
  INDUSTRY,
  COUNTRY_CODE,
  COUNTRY_NAME,
  REGION,
  IS_KEY_ACCOUNT,
  SEGMENT,
  IS_CURRENT
  -- NOTE: No PII columns (email, phone, address) in data product
FROM VERTIV_ANALYTICS.BI.DIM_CUSTOMER
WHERE IS_CURRENT = TRUE
;

CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.CUSTOMER_360.FEATURES_V1 AS
SELECT
  CUSTOMER_HK,
  AS_OF_DATE,
  FEATURE_VERSION,
  REV_L30D_USD,
  REV_L90D_USD,
  REV_L365D_USD,
  ORDER_COUNT_L90,
  AVG_ORDER_VALUE_L90,
  DAYS_SINCE_LAST_ORDER,
  ORDER_FREQUENCY_L365,
  CHURN_RISK_SCORE,
  UPSELL_PROPENSITY
FROM VERTIV_ANALYTICS.ML_FEATURES.CUSTOMER_REVENUE_FEATURES
;

-- ── PRODUCT 3: Revenue Analytics ─────────────────────────────
CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.REVENUE_ANALYTICS.MONTHLY_REVENUE_V1 AS
SELECT * FROM VERTIV_ANALYTICS.BI.MV_PRODUCT_REVENUE_MONTHLY
;

-- ── PRODUCT 4: Opportunity Signals ───────────────────────────
CREATE OR REPLACE SECURE VIEW VERTIV_PRODUCTS.OPPORTUNITY_SIGNALS.PREDICTIONS_V1 AS
SELECT
  ENTITY_HK,
  ENTITY_TYPE,
  AS_OF_DATE,
  MODEL_NAME,
  MODEL_VERSION,
  PREDICTION_LABEL,
  PREDICTION_SCORE,
  PREDICTION_BAND,
  CONFIDENCE_INTERVAL
FROM VERTIV_ANALYTICS.ML_FEATURES.MODEL_PREDICTIONS
WHERE MODEL_NAME IN ('CHURN_RISK','UPSELL_PROPENSITY')
;

-- ── CREATE SNOWFLAKE SHARES (Marketplace publishing) ──────────
USE ROLE ACCOUNTADMIN;

CREATE SHARE IF NOT EXISTS VERTIV_SALES_PERFORMANCE_SHARE
  ;

CREATE SHARE IF NOT EXISTS VERTIV_CUSTOMER_360_SHARE
  ;

-- Grant product schemas to shares
GRANT USAGE  ON DATABASE VERTIV_PRODUCTS                          TO SHARE VERTIV_SALES_PERFORMANCE_SHARE;
GRANT USAGE  ON SCHEMA   VERTIV_PRODUCTS.SALES_PERFORMANCE        TO SHARE VERTIV_SALES_PERFORMANCE_SHARE;


GRANT USAGE  ON DATABASE VERTIV_PRODUCTS                          TO SHARE VERTIV_CUSTOMER_360_SHARE;
GRANT USAGE  ON SCHEMA   VERTIV_PRODUCTS.CUSTOMER_360             TO SHARE VERTIV_CUSTOMER_360_SHARE;


-- To add a consumer (fill in actual Snowflake account ID at interview):
-- ALTER SHARE VERTIV_SALES_PERFORMANCE_SHARE ADD ACCOUNTS = <consumer_account_id>;

-- ── VERIFY ────────────────────────────────────────────────────
SHOW MASKING POLICIES IN SCHEMA VERTIV_CONFIG.METADATA;
SHOW ROW ACCESS POLICIES IN SCHEMA VERTIV_CONFIG.METADATA;
SHOW VIEWS IN SCHEMA VERTIV_PRODUCTS.SALES_PERFORMANCE;
SHOW VIEWS IN SCHEMA VERTIV_PRODUCTS.CUSTOMER_360;
SHOW SHARES;
